In [52]:
import pandas as pd
from sklearn.linear_model import LinearRegression
df=pd.read_csv('Melbourne_housing_FULL.csv(5.2.24).csv')
print(df)

           Suburb             Address  Rooms Type      Price Method  \
0      Abbotsford       68 Studley St      2    h        NaN     SS
1      Abbotsford        85 Turner St      2    h  1480000.0      S
2      Abbotsford     25 Bloomburg St      2    h  1035000.0      S
3      Abbotsford  18/659 Victoria St      3    u        NaN     VB
4      Abbotsford        5 Charles St      3    h  1465000.0     SP
...           ...                 ...    ...  ...        ...    ...
34852  Yarraville         13 Burns St      4    h  1480000.0     PI
34853  Yarraville       29A Murray St      2    h   888000.0     SP
34854  Yarraville      147A Severn St      2    t   705000.0      S
34855  Yarraville    12/37 Stephen St      3    h  1140000.0     SP
34856  Yarraville    3 Tarrengower St      2    h  1020000.0     PI

             SellerG        Date  Distance  Postcode  ...  Bathroom  Car  \
0             Jellis   3/09/2016       2.5    3067.0  ...       1.0  1.0
1             Biggin   3/12/2016       2.5    3067.0  ...       1.0  1.0
2             Biggin   4/02/2016       2.5    3067.0  ...       1.0  0.0
3             Rounds   4/02/2016       2.5    3067.0  ...       2.0  1.0
4             Biggin   4/03/2017       2.5    3067.0  ...       2.0  0.0
...              ...         ...       ...       ...  ...       ...  ...
34852            Jas  24/02/2018       6.3    3013.0  ...       1.0  3.0
34853        Sweeney  24/02/2018       6.3    3013.0  ...       2.0  1.0
34854            Jas  24/02/2018       6.3    3013.0  ...       1.0  2.0
34855  hockingstuart  24/02/2018       6.3    3013.0  ...       NaN  NaN
34856             RW  24/02/2018       6.3    3013.0  ...       1.0  0.0

       Landsize  BuildingArea  YearBuilt               CouncilArea Lattitude  \
0         126.0           NaN        NaN        Yarra City Council -37.80140
1         202.0           NaN        NaN        Yarra City Council -37.79960
2         156.0          79.0     1900.0        Yarra City Council -37.80790
3           0.0           NaN        NaN        Yarra City Council -37.81140
4         134.0         150.0     1900.0        Yarra City Council -37.80930
...         ...           ...        ...                       ...       ...
34852     593.0           NaN        NaN  Maribyrnong City Council -37.81053
34853      98.0         104.0     2018.0  Maribyrnong City Council -37.81551
34854     220.0         120.0     2000.0  Maribyrnong City Council -37.82286
34855       NaN           NaN        NaN  Maribyrnong City Council       NaN
34856     250.0         103.0     1930.0  Maribyrnong City Council -37.81810

       Longtitude             Regionname Propertycount
0       144.99580  Northern Metropolitan        4019.0
1       144.99840  Northern Metropolitan        4019.0
2       144.99340  Northern Metropolitan        4019.0
3       145.01160  Northern Metropolitan        4019.0
4       144.99440  Northern Metropolitan        4019.0
...           ...                    ...           ...
34852   144.88467   Western Metropolitan        6543.0
34853   144.88826   Western Metropolitan        6543.0
34854   144.87856   Western Metropolitan        6543.0
34855         NaN   Western Metropolitan        6543.0
34856   144.89351   Western Metropolitan        6543.0

[34857 rows x 21 columns]

In [55]:
df.nunique()

Suburb             351
Address          34009
Rooms               12
Type                 3
Price             2871
Method               9
SellerG            388
Date                78
Distance           215
Postcode           211
Bedroom2            15
Bathroom            11
Car                 15
Landsize          1684
BuildingArea       740
YearBuilt          160
CouncilArea         33
Lattitude        13402
Longtitude       14524
Regionname           8
Propertycount      342
dtype: int64

In [58]:
col=['Suburb','Rooms','Type','Method','SellerG','Distance','Bedroom2','Bathroom','Car','Landsize','BuildingArea','CouncilArea','Regionname','Propertycount','Price']
df=df[col]
df

,Suburb,Rooms,Type,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount,Price
0,Abbotsford,2,h,SS,Jellis,2.5,2.0,1.0,1.0,126.0,NaN,Yarra City Council,Northern Metropolitan,4019.0,NaN
1,Abbotsford,2,h,S,Biggin,2.5,2.0,1.0,1.0,202.0,NaN,Yarra City Council,Northern Metropolitan,4019.0,1480000.0
2,Abbotsford,2,h,S,Biggin,2.5,2.0,1.0,0.0,156.0,79.0,Yarra City Council,Northern Metropolitan,4019.0,1035000.0
3,Abbotsford,3,u,VB,Rounds,2.5,3.0,2.0,1.0,0.0,NaN,Yarra City Council,Northern Metropolitan,4019.0,NaN
4,Abbotsford,3,h,SP,Biggin,2.5,3.0,2.0,0.0,134.0,150.0,Yarra City Council,Northern Metropolitan,4019.0,1465000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,h,PI,Jas,6.3,4.0,1.0,3.0,593.0,NaN,Maribyrnong City Council,Western Metropolitan,6543.0,1480000.0
34853,Yarraville,2,h,SP,Sweeney,6.3,2.0,2.0,1.0,98.0,104.0,Maribyrnong City Council,Western Metropolitan,6543.0,888000.0
34854,Yarraville,2,t,S,Jas,6.3,2.0,1.0,2.0,220.0,120.0,Maribyrnong City Council,Western Metropolitan,6543.0,705000.0
34855,Yarraville,3,h,SP,hockingstuart,6.3,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,Western Metropolitan,6543.0,1140000.0
34856,Yarraville,2,h,PI,RW,6.3,2.0,1.0,0.0,250.0,103.0,Maribyrnong City Council,Western Metropolitan,6543.0,1020000.0

In [60]:
df.dropna(inplace=True)
df

,Suburb,Rooms,Type,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount,Price
2,Abbotsford,2,h,S,Biggin,2.5,2.0,1.0,0.0,156.0,79.0,Yarra City Council,Northern Metropolitan,4019.0,1035000.0
4,Abbotsford,3,h,SP,Biggin,2.5,3.0,2.0,0.0,134.0,150.0,Yarra City Council,Northern Metropolitan,4019.0,1465000.0
6,Abbotsford,4,h,VB,Nelson,2.5,3.0,1.0,2.0,120.0,142.0,Yarra City Council,Northern Metropolitan,4019.0,1600000.0
11,Abbotsford,3,h,S,Nelson,2.5,4.0,2.0,0.0,245.0,210.0,Yarra City Council,Northern Metropolitan,4019.0,1876000.0
14,Abbotsford,2,h,S,Nelson,2.5,2.0,1.0,2.0,256.0,107.0,Yarra City Council,Northern Metropolitan,4019.0,1636000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34847,Wollert,3,h,PI,Ray,25.5,3.0,2.0,2.0,383.0,118.0,Whittlesea City Council,Northern Metropolitan,2940.0,500000.0
34849,Wollert,3,h,SP,RW,25.5,3.0,2.0,2.0,404.0,158.0,Whittlesea City Council,Northern Metropolitan,2940.0,570000.0
34853,Yarraville,2,h,SP,Sweeney,6.3,2.0,2.0,1.0,98.0,104.0,Maribyrnong City Council,Western Metropolitan,6543.0,888000.0
34854,Yarraville,2,t,S,Jas,6.3,2.0,1.0,2.0,220.0,120.0,Maribyrnong City Council,Western Metropolitan,6543.0,705000.0
34856,Yarraville,2,h,PI,RW,6.3,2.0,1.0,0.0,250.0,103.0,Maribyrnong City Council,Western Metropolitan,6543.0,1020000.0

In [65]:
df.info()
df=pd.get_dummies(df,dtype='int')
df

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9244 entries, 2 to 34856
Columns: 630 entries, Rooms to Regionname_Western Victoria
dtypes: float64(8), int32(621), int64(1)
memory usage: 22.6 MB

,Rooms,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Propertycount,Price,Suburb_Abbotsford,...,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Regionname_Eastern Metropolitan,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
2,2,2.5,2.0,1.0,0.0,156.0,79.0,4019.0,1035000.0,1,...,1,0,0,0,1,0,0,0,0,0
4,3,2.5,3.0,2.0,0.0,134.0,150.0,4019.0,1465000.0,1,...,1,0,0,0,1,0,0,0,0,0
6,4,2.5,3.0,1.0,2.0,120.0,142.0,4019.0,1600000.0,1,...,1,0,0,0,1,0,0,0,0,0
11,3,2.5,4.0,2.0,0.0,245.0,210.0,4019.0,1876000.0,1,...,1,0,0,0,1,0,0,0,0,0
14,2,2.5,2.0,1.0,2.0,256.0,107.0,4019.0,1636000.0,1,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34847,3,25.5,3.0,2.0,2.0,383.0,118.0,2940.0,500000.0,0,...,0,0,0,0,1,0,0,0,0,0
34849,3,25.5,3.0,2.0,2.0,404.0,158.0,2940.0,570000.0,0,...,0,0,0,0,1,0,0,0,0,0
34853,2,6.3,2.0,2.0,1.0,98.0,104.0,6543.0,888000.0,0,...,0,0,0,0,0,0,0,0,1,0
34854,2,6.3,2.0,1.0,2.0,220.0,120.0,6543.0,705000.0,0,...,0,0,0,0,0,0,0,0,1,0
34856,2,6.3,2.0,1.0,0.0,250.0,103.0,6543.0,1020000.0,0,...,0,0,0,0,0,0,0,0,1,0

In [63]:
X=df.drop(columns=['Price'])
Y=df['Price']
X
Y

2        1035000.0
4        1465000.0
6        1600000.0
11       1876000.0
14       1636000.0
           ...
34847     500000.0
34849     570000.0
34853     888000.0
34854     705000.0
34856    1020000.0
Name: Price, Length: 9244, dtype: float64

In [67]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)
from sklearn.linear_model import LinearRegression
reg1=LinearRegression()
reg1.fit(X_train,Y_train)

LinearRegression()

In [68]:
reg1.score(X_train,Y_train)
reg1.score(X_test,Y_test)

-2315895302981.922

In [72]:
from sklearn.linear_model import Lasso
reg2=Lasso(alpha=25,max_iter=100,tol=0.1)
reg2.fit(X_train,Y_train)

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 389674972785735.6, tolerance: 297465860482348.94
  model = cd_fast.enet_coordinate_descent(

Lasso(alpha=25, max_iter=100, tol=0.1)

In [73]:
reg2.score(X_train,Y_train)

0.7468590316176442

In [74]:
reg2.score(X_test,Y_test)

0.6586859653269364

In [78]:
from sklearn.linear_model import Ridge
reg3=Ridge(alpha=25,max_iter=100,tol=0.1)
reg3.fit(X_train,Y_train)

Ridge(alpha=25, max_iter=100, tol=0.1)

In [79]:
reg3.score(X_train,Y_train)

0.7143454730606782

In [80]:
reg3.score(X_test,Y_test)

0.6559828552589946